language: go
go: 1.12.x 
git:
  submodules: false
env:
- GO111MODULE=on
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y make unzip
- sudo curl -L https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip -o /usr/local/bin/tf.zip
- cd /usr/local/bin && sudo unzip tf.zip
install: true
script:
#- make bootstrap
#- make test
